# Railway Configuration for REC
# Defines multiple services: web (Next.js) and worker (BullMQ)

[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm prisma generate && pnpm build"

# Smart start command - uses SERVICE_TYPE env var to decide
[deploy]
startCommand = "bash scripts/railway-start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
