# Railway Configuration for REC
# Defines multiple services: web (Next.js) and worker (BullMQ)

[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm prisma generate && pnpm build"

# Web Service (Next.js App)
[deploy]
startCommand = "pnpm worker"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
